stages:
  prepare:
    cmd: python src/steps/prepare.py data/raw/ data/prepared
    deps:
    - data/raw
    - src/steps/prepare.py
    outs:
    - data/prepared

  split:
    cmd: python src/steps/split.py data/prepared/ data/split
    deps:
    - data/prepared
    - src/steps/prepare.py
    outs:
    - data/split

  train_baseline_model:
    cmd: python src/steps/train_baseline_model.py data/split/train.csv data/split/test.csv
    deps:
    - data/split/train.csv
    - data/split/test.csv
    - src/steps/train_baseline_model.py
    outs:
    - data/models/baseline
    
  train_collaborative_filtering:
    cmd: python src/steps/train_collaborative_filtering.py data/split/train.csv data/split/test.csv
    deps:
    - data/split/train.csv
    - data/split/test.csv
    - src/steps/train_collaborative_filtering.py
    outs:
    - data/models/CollaborativeFiltering

  train_factorization:
    cmd: python src/steps/train_factorization.py data/split/train.csv data/split/test.csv
    deps:
    - data/split/train.csv
    - data/split/test.csv
    - src/steps/train_factorization.py
    outs:
    - data/models/MatrixFactorization

  train_content_based:
    cmd: python src/steps/train_content_based.py data/split/train.csv data/split/test.csv
    deps:
    - data/split/train.csv
    - data/split/test.csv
    - src/steps/train_content_based.py
    outs:
    - data/models/ContentBasedFiltering

  evaluate:
    cmd: python src/steps/evaluate.py data/split/test.csv data/prepared/preprocessed.csv
    deps:
    - data/split/test.csv
    - data/prepared/preprocessed.csv
    - src/steps/evaluate.py
    - data/models
    metrics:
    - data/eval/metrics.json:
        cache: false
