stages:
  prepare:
    cmd: python src/steps/prepare.py data/BX-Book-Ratings.csv data/prepared/BX-Book-Ratings-Prepared.csv
    deps:
    - data/BX-Book-Ratings.csv
    - src/steps/prepare.py
    outs:
    - data/prepared
