stages:
  prepare:
    cmd: python src/steps/prepare.py data/raw/ data/prepared
    deps:
    - data/raw
    - src/steps/prepare.py
    outs:
    - data/prepared

  split:
    cmd: python src/steps/split.py data/prepared/ data/split
    deps:
    - data/prepared
    - src/steps/prepare.py
    outs:
    - data/split

  train:
    cmd: python src/steps/train.py data/split/train.csv data/split/test.csv
    deps:
    - data/split/train.csv
    - data/split/test.csv
    - src/steps/train.py
    outs:
    - data/models

  evaluate:
    cmd: python src/steps/evaluate.py data/split/test.csv 
    deps:
    - data/split/test.csv
    - src/steps/evaluate.py
    - data/models
    metrics:
    - data/eval/metrics.json:
        cache: false
