filter_treshold: 10
rating_filter: 5
user_column: User-ID
book_column: ISBN
rating_column: Book-Rating

prepare:
  users_file: BX-Users.csv
  book_file: BX-Books.csv
  rate_file: BX-Book-Ratings.csv

split:
  train_size: 0.75
  test_size: 0.10
  seed: 20170428
  stratify_column: ISBN

train:
  method: mean
  transformer_model: all-mpnet-base-v2
  num_epochs: 100
  patience: 3
  min_delta: 0.001
  train_file: 'train.csv'
  test_file: 'test.csv'
  val_file: 'val.csv'

evaluate:
  k_list:
  - 5
  - 10
  - 20
