prepare:
  users_file: BX-Users.csv
  book_file: BX-Books.csv
  rate_file: BX-Book-Ratings.csv

split:
  train_size: 0.70
  test_size: 0.30
  seed: 20170428
  stratify_column: ISBN

train:
  model: CollaborativeFiltering
  method: mean
  filter_treshold: 50

evaluate:
  user_column: User-ID
  book_column: ISBN
  k_list:
  - 5
  - 10
  - 15
