mapping_dict = {
    '': 'other',
    '01776': 'usa',
    '02458': 'usa',
    '19104': 'usa',
    '23232': 'usa',
    '30064': 'usa',
    '85021': 'usa',
    '87510': 'usa',
    'alachua': 'usa',
    'america': 'usa',
    'austria': 'australia',
    'autralia': 'australia',
    'cananda': 'canada',
    'geermany': 'germany',
    'italia': 'italy',
    'united kindgonm': 'united kingdom',
    'united sates': 'usa',
    'united staes': 'usa',
    'united state': 'usa',
    'united states': 'usa',
    'us': 'usa',
    'u.a.e': 'united arab emirates',
    'españa': 'spain',
    'london': 'united kingdom',
    'basque country': 'spain',
    'la france': 'france',
    'france"': 'france',
    'l`italia': 'italy',
    'sicilia': 'italy',
    'itlay': 'italy',
    'united statea': 'usa',
    'canda': 'canada',
    'la svizzera': 'switzerland',
    'switzerland"': 'switzerland',
    'u.s.a!': 'usa',
    '&#20013;&#22269;': 'other',
    '&#32654;&#22269;': 'other',
    '*': 'other',
    '-': 'other',
    '-------': 'other',
    '.': 'other',
    '5057chadwick ct.': 'other',
    '?ú?{': 'other',
    '\\"n/a\\"': 'other',
    '\\n/a\\"': 'other',
    '_ brasil': 'brazil',
    'a': 'other',
    'aaa': 'other',
    'adsgfdr': 'other',
    'good old usa !': 'usa',
    'united stated': 'usa',
    'united stated of america': 'usa',
    'united states of america': 'usa',
    'u.s. of a.': 'usa',
    'u.s. virgin islands': 'usa',
    'u.s.a.': 'usa',
    'u.s.a>': 'usa',
    'u.s>': 'usa',
    'ukrain': 'ukraine',
    'california': 'usa',
    'uusa': 'usa',
    'burlington': 'canada',
    'wonderful usa': 'usa',
    'can': 'canada',
    'canada eh': 'canada',
    'le canada': 'canada',
    'united kindgdom': 'united kingdom',
    'united kingdom"': 'united kingdom',
    'united kingdom.': 'united kingdom',
    'england': 'united kingdom',
    'u k': 'united kingdom',
    'uk': 'united kingdom',
    'u.k.': 'united kingdom',
    'bavaria': 'germany',
    'germany"': 'germany',
    'germay': 'germany',
    'spain"': 'spain',
    'espanha / galiza': 'spain',
    'espaã?â±a': 'spain',
    'espaã±a': 'spain',
    'españa"': 'spain',
    'catalonia': 'spain',
    'catalunya': 'spain',
    'catalunya spain': 'spain',
    'catalunya(catalonia)': 'spain',
    'deutsches reich': 'germany',
    'deutschland': 'germany',
    'deutschland"': 'germany',
    'portugal"': 'portugal',
    'saudia arabia': 'saudi arabia',
    'finland"': 'finland',
    'brasil': 'brazil',
    'brazil"': 'brazil',
    'australia"': 'australia',
}
